environment:
  matrix:
  # node.js
  - nodejs_version: "4"
  - nodejs_version: "5"
  - nodejs_version: "0.12"
  # io.js
  - nodejs_version: "1.0"
  
platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
